name: "Push to gh pages"

on: workflow_dispatch

run-name: Push to gh pages from ${{ github.ref_name }}

jobs:
  dedupe_deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci
        shell: bash

      - name: Build website
        run: npm run build

      - name: Publishing doc
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: BlackySoul/gh-push-test
          token: ${{ secrets.GH_TEST_GITHUB_TOKEN }}
          branch: main
          folder: out
          clean: false
          force: false
