name: "Build"

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci
        shell: bash

      - name: Build website
        run: npm run build
        env:
          NEXT_PUBLIC_BASE_PATH: /gh-push-test/1.0.0
          NEXT_PUBLIC_DIST_DIR: out/1.0.0

      - name: Publishing doc
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: BlackySoul/gh-push-test
          token: ${{ secrets.GH_TEST_GITHUB_TOKEN }}
          branch: main
          folder: out
          clean: false
          force: false
